<?xml version="1.0"?> 
<!DOCTYPE bookstore [ 
<!ELEMENT bookstore (book)> 
<!ELEMENT book (bookname,bookprice,bookauthor,booknumber,pages)> 
<!ELEMENT bookname (#PCDATA)> 
<!ELEMENT bookprice (#PCDATA)> 
<!ELEMENT bookauthor (#PCDATA)> 
<!ELEMENT booknumber (#PCDATA)> 
 
<!ELEMENT pages (#PCDATA)> 

]> 


<bookstore>
<book>
<bookname> The Taking of Jake Livingston </bookname>
<bookauthor>Ayana Gray</bookauthor>
<bookprice>$499</bookprice>
<ISBN>23456</ISBN>
<pages>500</pages>
</book>
<book>
<bookname> All Our Hidden Gifts </bookname>
<bookauthor>Caroline Oâ€™Donoghue</bookauthor>
<bookprice>$400</bookprice>
<ISBN>76156</ISBN>
<pages>180</pages>
</book>
<book>
<bookname>When Shadows Fall</bookname>
<bookauthor> Sita Bramachari</bookauthor>
<bookprice>$300</bookprice>
<ISBN>98456</ISBN>
<pages>300</pages>
</book>
<book>
<bookname> Hawk </bookname>
<bookauthor> James Patterson</bookauthor>
<bookprice>$450</bookprice>
<ISBN>12456</ISBN>
<pages>200</pages>
</book>
<book>
<bookname> Mind Your Head </bookname>
<bookauthor> Juno Dawson</bookauthor>
<bookprice>$350</bookprice>
<ISBN>73456</ISBN>
<pages>300</pages>
</book>
</bookstore>
